import { BookOpen, Library, Menu, ShieldCheck, UserRound, X } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
import { Badge } from './ui/Badge'
import { Button } from './ui/Button'
import { Input } from './ui/Field'

const navClass = ({ isActive }: { isActive: boolean }) => `rounded-lg px-3 py-2 text-sm font-medium transition ${isActive ? 'bg-brand-50 text-brand-700' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`
export function Layout() {
  const { userId, setUserId, userName, roles, isLoading, userError, hasRole } = useAuth(); const [draft, setDraft] = useState(userId); const [open, setOpen] = useState(false)
  const nav = <><NavLink className={navClass} to="/books">도서 둘러보기</NavLink>{hasRole('BORROWER') && <NavLink className={navClass} to="/borrower/requests">내 대여 요청</NavLink>}{hasRole('LENDER') && <NavLink className={navClass} to="/lender/books">내 책 관리</NavLink>}{hasRole('ADMIN') && <><NavLink className={navClass} to="/admin/dashboard">대시보드</NavLink><NavLink className={navClass} to="/admin/books/pending">책 승인</NavLink><NavLink className={navClass} to="/admin/borrow-requests">요청 관리</NavLink><NavLink className={navClass} to="/admin/loans">대출 관리</NavLink></>}</>
  return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-3 lg:px-8"><NavLink to="/" className="flex items-center gap-2 font-bold"><span className="rounded-lg bg-brand-600 p-2 text-white"><BookOpen className="h-5 w-5"/></span><span>BookBridge</span></NavLink><nav className="hidden flex-1 items-center gap-1 lg:flex">{nav}</nav><button className="ml-auto lg:hidden" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button><div className="hidden items-center gap-2 lg:flex"><Input className="w-24" inputMode="numeric" value={draft} onChange={e => setDraft(e.target.value)} placeholder="사용자 ID"/><Button onClick={() => setUserId(draft.trim())}>적용</Button></div></div>{open && <nav className="flex flex-col gap-1 border-t p-4 lg:hidden">{nav}<div className="mt-2 flex gap-2"><Input inputMode="numeric" value={draft} onChange={e => setDraft(e.target.value)} placeholder="사용자 ID"/><Button onClick={() => { setUserId(draft.trim()); setOpen(false) }}>적용</Button></div></nav>}<div className="border-t border-slate-100 bg-slate-50"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-2 px-4 py-2 text-xs text-slate-600 lg:px-8"><UserRound className="h-4 w-4"/><span>{!userId ? '사용자 ID 미설정' : isLoading ? '사용자 확인 중…' : userError ? `ID ${userId} 사용자를 찾을 수 없음` : `${userName} · ID ${userId}`}</span>{roles.map(role => <Badge key={role} value={role}/>)}<span className="ml-auto hidden items-center gap-1 sm:flex"><ShieldCheck className="h-4 w-4"/>역할 기반 메뉴는 UX용이며 보안 검증은 서버에서 수행합니다.</span></div></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8"><Outlet/></main><footer className="border-t bg-white"><div className="mx-auto flex max-w-7xl items-center gap-2 px-4 py-6 text-xs text-slate-500 lg:px-8"><Library className="h-4 w-4"/>BookBridge Frontend · Spring Boot API 연동</div></footer></div>
}
