# 개발환경
# profile
spring.config.activate.on-profile=dev

# server
server.port=8080

#DB
#spring.datasource.driver-class-name=cubrid.jdbc.driver.CUBRIDDriver
#spring.datasource.url=jdbc:cubrid:localhost:30000:alr20:::?charset=UTF-8
#spring.datasource.data-username=alr20
#spring.datasource.data-password=alr20


#spring.datasource.driver-class-name= oracle.jdbc.driver.OracleDriver
#spring.datasource.url= jdbc:oracle:thin:@12.4.96.150:1622:AFDEV
#spring.datasource.username= OJT
#spring.datasource.password= roqkfeo#01
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
spring.datasource.driver-class-name: org.h2.Driver
spring.datasource.url: jdbc:h2:mem:alr20
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql=trace



#spring.datasource.hikari.connection-test-query= select 1
spring.jackson.serialization.fail-on-empty-beans=false

#security

#thymeleaf
spring.thymeleaf.cache=false

#pageable
spring.data.web.pageable.max-page-size=10
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.one-indexed-parameters=true

#error
server.error.include-exception=true
server.error.include-stacktrace=always
server.error.whitelabel.enabled=false

#logging.level.org.springframework.security=DEBUG

#logging
logging.file.name=logs/dev_app.log
logging.level.root=info
logging.level.mil.af.service=debug
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.session_factory.statistics.log_summary=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.session_factory.statement_inspector=mil.af.jpaquerycounter.JpaInspector
