# 운영환경
# profile
spring.config.activate.on-profile=prod

# server
server.port=8080
#spring.main.web-application-type=none
logging.level.org.springframework.boot.context.web.ErrorPageFilter=off

#DB
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=420000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=10000

#????
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=100MB
spring.tomcat.max-http-post-size=104857600

#Cubrid
spring.datasource.driver-class-name=cubrid.jdbc.driver.CUBRIDDriver
spring.datasource.url=jdbc:cubrid:12.134.160.52:30000:alr20:alr20:1q2w3e4r!:?charset=UTF-8
spring.datasource.data-username=alr20
spring.datasource.data-password=1q2w3e4r!
spring.jpa.database-platform=org.hibernate.dialect.CUBRIDDialect


#JPA
spring.jpa.hibernate.ddl-auto=update
# 시험평가때는 update, 운영환경에서는 none 세팅하기
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
#logging.level.org.hibernate.type.descriptor.sql=trace

spring.datasource.hikari.connection-test-query= select 1
spring.jackson.serialization.fail-on-empty-beans=false

#security

#thymeleaf
spring.thymeleaf.cache=false

#pageable
spring.data.web.pageable.max-page-size=10
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.one-indexed-parameters=true

#error
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false

#logging
logging.file.name=logs/prod_app.log
logging.level.root=info
logging.level.mil.af.service=debug