# 환경 분리
spring.profiles.default=dev

# context path
server.servlet.context-path=/alr20

file.pw=75e916cb-31de!
file.judge-pw=-f$^*

# Hangul i kkae gym.... So we use English
# Encryption Method : AES-256 && We must fix the legnth of key to 32 bytes(256bit)
AES.key=roqkfeo01wjsgodxla99!@#qlalfqjsg


// ??? ? ?? ?? 30?
server.servlet.session.timeout=30m
