import { useQuery } from '@tanstack/react-query'
import { borrowerApi } from '../api/endpoints'
import { getApiError } from '../api/client'
import { RequireRole } from '../components/RequireRole'
import { PageHeader } from '../components/PageHeader'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { EmptyState, ErrorAlert, LoadingState } from '../components/ui/Feedback'
import { formatDate } from '../utils/format'
import { useAuth } from '../features/auth/AuthContext'
export function BorrowerRequestsPage(){const {userId,hasRole}=useAuth();const q=useQuery({queryKey:['borrower-requests',userId],queryFn:borrowerApi.requests,enabled:hasRole('BORROWER')});return <RequireRole role="BORROWER"><PageHeader title="내 대여 요청" description="요청 처리 상태를 확인할 수 있습니다."/>{q.isLoading?<LoadingState/>:q.isError?<ErrorAlert message={getApiError(q.error)}/>:!q.data?.length?<EmptyState title="아직 대여 요청이 없습니다."/>:<div className="space-y-3">{q.data.map(r=><Card key={r.id} className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-bold">{r.bookTitle}</h2><Badge value={r.status}/></div><p className="mt-2 text-sm text-slate-500">수량 {r.quantity}권 · 요청 {formatDate(r.requestedAt)}</p></div><span className="text-xs text-slate-400">요청 #{r.id}</span></Card>)}</div>}<Card className="mt-6 border-dashed bg-slate-50"><h2 className="font-semibold">내 대출 이력</h2><p className="mt-2 text-sm text-slate-600">TODO: 현재 백엔드에는 BORROWER 본인의 대출 이력을 조회하는 API가 없어 연결하지 않았습니다.</p></Card></RequireRole>}
