import { Navigate, Route, Routes } from 'react-router-dom'
import { Layout } from './components/Layout'
import { AdminBorrowRequestsPage } from './pages/AdminBorrowRequestsPage'
import { AdminDashboardPage } from './pages/AdminDashboardPage'
import { AdminLoansPage } from './pages/AdminLoansPage'
import { AdminOverdueLoansPage } from './pages/AdminOverdueLoansPage'
import { AdminPendingBooksPage } from './pages/AdminPendingBooksPage'
import { BookDetailPage } from './pages/BookDetailPage'
import { BooksPage } from './pages/BooksPage'
import { BorrowerRequestsPage } from './pages/BorrowerRequestsPage'
import { HomePage } from './pages/HomePage'
import { LenderBookFormPage } from './pages/LenderBookFormPage'
import { LenderBooksPage } from './pages/LenderBooksPage'
import { NotFoundPage } from './pages/NotFoundPage'
export default function App(){return <Routes><Route element={<Layout/>}><Route path="/" element={<HomePage/>}/><Route path="/books" element={<BooksPage/>}/><Route path="/books/:bookId" element={<BookDetailPage/>}/><Route path="/borrower/requests" element={<BorrowerRequestsPage/>}/><Route path="/lender/books" element={<LenderBooksPage/>}/><Route path="/lender/books/new" element={<LenderBookFormPage/>}/><Route path="/lender/books/:bookId/edit" element={<LenderBookFormPage/>}/><Route path="/admin/dashboard" element={<AdminDashboardPage/>}/><Route path="/admin/books/pending" element={<AdminPendingBooksPage/>}/><Route path="/admin/borrow-requests" element={<AdminBorrowRequestsPage/>}/><Route path="/admin/loans" element={<AdminLoansPage/>}/><Route path="/admin/loans/overdue" element={<AdminOverdueLoansPage/>}/><Route path="/admin" element={<Navigate to="/admin/dashboard" replace/>}/><Route path="*" element={<NotFoundPage/>}/></Route></Routes>}
